version: '3.1'

networks:
  green_frontend:
    external: true
  blue_frontend:
    external: true

services:
  bg:
    image: 127.0.0.1:5000/bg-nginx
    hostname: bg
    ports:
      - "80:80"
    networks:
      - green_frontend
      - blue_frontend



